server:
  port: 8100

spring:
  application:
    name: payment-method

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
<<<<<<< HEAD
  secret-key: ${stripe.key}
=======
  secret-key: sk_test_
>>>>>>> a114d8b (readme added)
